# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b8bcf84715ae71dc4dbe957b622c71155893e30ca47da3c2c553e668f056b7309ffe2669df17dea08041cc3004347803f4722ddfec40e8c4216f1c3e7293e3

test:
  secret_key_base: bf54b372371017c568062b04a8dc4386829a0a344fec584b748e2068cf0c0881464a94ee21f851dea5c5e93205df6e20bab7fee6a4148c7ab025055e21f9c4ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
